<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
<script src="bootstrap/js/bootstrap.min.js"></script>

<style>
    body:before {
        background-image: url('img/paper.jpg');
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        z-index: 0;
        opacity: 0.5;
    }
</style>
