<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
<script src="bootstrap/js/bootstrap.min.js"></script>

<style>
    body {
        background-image: url('img/paper-2.jpg');
        background-repeat: repeat;
        background-position: center center;
        background-size: 100%;
        /*content: "";*/
        /*position: absolute;*/
        /*width: 100%;*/
        /*height: 150%;*/
        /*z-index: 0;*/
        /*opacity: 0.5;*/
    }
</style>
